Follow latest upper-constraints rules
ERROR: Editable requirements are not allowed as constraints

Change-Id: Iee28dcabbffedaa97457793907b3b7518f2bae85
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 565e145cce0e2d1fce3b832f3c2060e3e81338d7)